export const CODIGO_ESTADO_FACTURACION_PENDIENTE = 'PENDIENTE';
export const CODIGO_ESTADO_FACTURACION_FACTURADA = 'FACTURADA';

export const ID_ESTADO_FACTURACION_PENDIENTE = '000001';
export const ID_ESTADO_FACTURACION_FACTURADA = '000002';
